# 微信公众号配置
WeChat:
  AppId: xxxxxxx # 公众号 AppId
  AppSecret: xxxxxxx # 公众号 AppSecret
# 阿里与OSS上传配置
OSS:
  EndPoint: oss-cn-hangzhou.aliyuncs.com # oss EndPoint
  AccessKeyID: xxxxx
  AccessKeySecret: xxxxx
  BucketName: xxxxxxx
# MySQL连接配置
DataBase:
  Driver: mysql   # 数据库驱动
  Host: xxxxxxx   # 主机地址
  Port: 3306      # 端口
  User: xxxxxxx   # 用户
  Pass: xxxxxxx   # 密码
  DBName: xxxxxxx # 数据库名称